### ISSUE TITLE
LTI: Invalid signature

### ISSUE THREAD

**Issue by aroos** [abelardopardo/ontask_b#116] opened 2019-01-03 22:00 UTC
University of Adelaide is currently experimenting with V4 beta (Canvas Email).

Previously LTI connectivity was working, unfortunately with the V4 beta version it stopped working and reports "Invalid signature".

Is the LTI functionality working for anyone with this version?

**Comment by abelardopardo** [comment] 2019-01-04 03:53
This may be related to the upgrade to Python 3. I need to investigate further. Thanks for the heads up.

**Comment by abelardopardo** [comment] 2019-01-14 09:08
Confirmed. This is a bug due to the migration from Python 2 to 3. The comparison between the types str and bytes are different in Python 3. Exploring the fix.

**Comment by abelardopardo** [comment] 2019-01-15 06:15
@aroos The beta now contains a fix addressing this problem. It has been tested using the LTI connection with edX as producer and it worked. Would you be able to confirm it works in Canvas as well?

**Comment by abelardopardo** [comment] 2019-02-14 05:36
Issue fixed in release 4.0

**Closed by abelardopardo** 2019-02-14 05:36 UTC
Labels: bug, fix on next release
