### ISSUE TITLE
Sort by "Last Modified" doesn't sort correctly

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#118] opened 2019-01-21 19:22 UTC
Both ascending and descending don't seem to work. Perhaps it's sorting on a different timestamp (or a subset) than the one that's being displayed?

![screen shot 2019-01-21 at 11 20 47 am](https://user-images.githubusercontent.com/2507459/51494744-a6968080-1d6e-11e9-9944-437bd12ebdcc.png)

**Comment by abelardopardo** [comment] 2019-01-23 00:15
Can you please clarify the table in which this column appear? Thanks

**Comment by firasm** [comment] 2019-01-23 05:13
It's in the first table, the list of workflows when a user first logs in. The page title is: "Open or create a workflow*"

(Sorry, my mistake should have included that)

**Comment by abelardopardo** [comment] 2019-01-24 06:11
No problem. That table has been now changed by a list of "cards" in version 4.0.0 (in Beta right now). I reviewed though the sorting criteria for other tables with this type of column and appears to be working. I'll close the issue after the next release and you check that the problem is gone.

**Comment by abelardopardo** [comment] 2019-02-14 05:36
Issue fixed in release 4.0

**Closed by abelardopardo** 2019-02-14 05:36 UTC
Labels: fix on next release
