### ISSUE TITLE
edit table row data with empty value in key field 

### ISSUE THREAD

**Issue by whol019** [abelardopardo/ontask_b#142] opened 2019-03-28 03:20 UTC
We had an academic merged data from gradebook, but forgot to remove test student record. As test student has no email address, the academic tried to delete the row, but the delete function,  in table/views.py/row_delete() , with empty key value it will display "incorrect URL invoked to delete a row" message ...
when tried to edit the row, key fields are readonly, so he could not update it too.
=> ** we hope the  table update row function,  empty key fields could be allowed to update( not readonly ).**
=> **also hope that action can be shared or reused.**
The academic later recreated another workflow, but found out actions could not be reused and had to recreate conditions/actions etc again, in the end he spent more than 4 hours for preparing the mailout.

**Comment by abelardopardo** [comment] 2019-03-30 06:38
Hi. A few comments

1) Can you please specify the version you are using?

2) A key field should not have an empty value. If that is the case, it is a glitch in the system. A key column needs to have all values in order to distinguish rows. If you could describe the steps you followed to obtain the empty key column cell, that would be fantastic. Editing the key fields will not be allowed as changes may leave the data frame in inconsistent state. There is a way to edit the field by simply removing the "key" attribute in the column (edit column). This is only allowed as long as there is another column with the key property. The limitations imposed by the tool are: a) there must be at least a key column, and 2) the key column is not editable (additionally, all rows in this column should be non empty).

3) The actions can be "exported" and then imported into another workflow. This functionality is already present and has been tested. Let me know if you find any other problems.

**Comment by abelardopardo** [comment] 2019-03-31 00:02
Another functionality that you may find useful is the possibility of cloning an action. It creates a duplicate of all actions and conditions so you don't have to start from scratch. Very useful when the conditions and/or the text are similar.

**Comment by abelardopardo** [comment] 2019-04-15 05:09
I found a case in which the first problem (an empty value creeping in a key or unique column) can happen. Working on a fix.

**Comment by abelardopardo** [comment] 2019-04-16 08:12
Fixed in release B.4.3

**Closed by abelardopardo** 2019-04-16 08:12 UTC
Labels: bug, fix on next release
