### ISSUE TITLE
Error in Canvas Oauth flow in v6.1.1

### ISSUE THREAD

**Issue by andrew-gardener** [abelardopardo/ontask_b#173] opened 2019-11-01 22:37 UTC
**Describe the bug**
The action's info is not being stored in the session when when triggering the oauth flow for canvas messages (missing `target_url` triggers error [here](https://github.com/abelardopardo/ontask_b/blob/master/ontask/oauth/views.py#L164). 

**Additional context**
This is very similar to #151 / #152 with a similar potential fix of moving the `set_action_payload(req.session, action_info.get_store())` from [here](https://github.com/abelardopardo/ontask_b/blob/master/ontask/action/views/run_canvas_email.py#L74) to [here](https://github.com/abelardopardo/ontask_b/blob/master/ontask/action/views/run_canvas_email.py#L78).

Not sure what the actual issue and fix was last time but I think it might be a good idea to ensure that the action's info is properly stored at the above mentioned point since this issue has cropped up twice now.

**Comment by abelardopardo** [comment] 2019-11-02 04:02
Agree. The problem is actually to create an accurate mock up of the OAuth client so that we can include it as part of the regression test and detect deviations. Need to think a bit more about it.

Issue fixed in 6.1.2

**Closed by abelardopardo** 2019-11-02 04:02 UTC
Labels: Bug
