### ISSUE TITLE
Data merge fails when key column names and values don't match

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#41] opened 2018-05-17 21:25 UTC
Error is

`Merge operation failed. (New values in column student id are not of type integer)`

A minimal dataset is attached.

Steps to reproduce:
1. upload A1
2. merge A2 on `student id` in the existing table, `sis id` in the new table, using either merge method 1 or 4 (Merge methods 2 and 3 work.)

All 4 merge methods work as expected if the column `sis id` in A2 is renamed to `student id`.

This issue highlights that the values in the key columns are not "merged" when the column names are different, but the values *are* merged when the columns have the same name. This behaviour is not made clear to the user.

[issue41.zip](https://github.com/abelardopardo/ontask_b/files/2014786/issue41.zip)

**Comment by abelardopardo** [comment] 2018-05-18 07:10
Thanks for providing the test case. The answer provided by the platform is incorrect. The correct behavior is:

Method 1) The merge fails because the key column in the existing table ends up with an undefined value (because the new key column has an extra one, it is not being renamed, and therefore, they are kept separately). This is **different** from the current behavior where a data type problem is incorrectly shown as the cause for the failure to merge [BUG]

Method 2) Merge should go through with no problem because the intersection of the columns is taken, so all key columns end up with correct values.

Method 3) Merge should go through with no problem because we are taking the keys in the existing table, and this column has correct values.

Method 4) The merge should fail for the same reason as Method 1, the key column in the existing table ends up with an undefined value (due to the new value in the key column of the new table). This is **different** from the current behavior [BUG]

The new behavior will be included in the next release.

**Comment by abelardopardo** [comment] 2018-05-23 04:51
Solved in Version 2.6.1

**Closed by abelardopardo** 2018-05-23 04:51 UTC
Labels: bug, fix on next release
