### ISSUE TITLE
Merge with different key column names: both columns in result

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#39] opened 2018-05-16 19:07 UTC
My initial data import contains 2 columns `email` and `sis id`:

![screen shot 2018-05-16 at 11 39 52 am](https://user-images.githubusercontent.com/6002755/40136890-e4cc428a-58fd-11e8-8c6c-4b7c6ee19b70.png)

I want to merge with a second data file that has a different key column name: `student id`:

![screen shot 2018-05-16 at 11 41 27 am](https://user-images.githubusercontent.com/6002755/40136946-17e586b8-58fe-11e8-97f8-6da82078f76b.png)

I specify to merge on the key columns `sis id` in the Existing Table, and `student id` in the New Table:

![screen shot 2018-05-16 at 11 42 36 am](https://user-images.githubusercontent.com/6002755/40137012-421b6d12-58fe-11e8-88f1-32d730e524d6.png)

The merge preview suggests that rows will be matched on `sis id` = `student id`, A1 will be a new column in the Existing table, and `email` will be unchanged:

![screen shot 2018-05-16 at 11 45 03 am](https://user-images.githubusercontent.com/6002755/40137178-992ffe92-58fe-11e8-88c2-4b8b6115eff3.png)

 The result (surprisingly) includes all 4 columns:

![screen shot 2018-05-16 at 11 45 25 am](https://user-images.githubusercontent.com/6002755/40137202-a6d7b4cc-58fe-11e8-803c-959e40eff026.png)

The table merge visualization at Step 3 and the preview at Step 4 both suggest a single key column in the result. If  a 4-column result is the intended behaviour, it should be made more clear in the previews at Steps 3 and 4 in the merge process.

**Comment by abelardopardo** [comment] 2018-05-17 01:56
Wait. This is not a bug. You have two different columns that you want to match up, but not necessarily drop one of them. Which one would you drop? 

Think for example a scenario in which both columns do not have 100% overlap. You may have student id with 100 students and sis id with 90 students. The merge would still go through correctly and then you could choose one and drop the other.

The user can always delete columns, but for the merge to assume this, is too much (unless of course they match in name entirely, then it is clear what to do.

Curious about your thoughts...

**Comment by craigdsthompson** [comment] 2018-05-17 21:30
I'm not 100% convinced it's necessarily a "bug" in how the merge is executed, but certainly a behaviour that was not anticipated/expected after reading the documentation and observing the merge previews at steps 3 and 4. Step 4, in particular, is not clear. The arrow icon suggests that values from the `student id` column will be merged *into* the `sis id` column in the existing table. The preview at step 4 suggests 3 columns in the final table, when there are actually 4 in the output. One solution to this issue is to revise the preview at step 4 to show all 4 columns that will be in the resulting table.

Ideally, all my data sources would have consistent naming conventions, and the same column name (such as `student id`) would be used everywhere. Then there would be no problem because OnTask does not create 2 key columns in the result when the column names match. So, a second "solution" to this issue is to be more heavy handed about suggesting/warning/insisting that consistent column naming conventions are used, such as only allowing joins on columns with the same name or warning users when different column names are used. Alternatively, as part of the file upload/merge process the user could be prompted to rename the merge column.

Regarding your scenario: I believe this is (or should be) the purpose of the dropdown with 4 merge methods. When the values in the chosen key columns don't map 1-1 with perfect overlap, the user can select to keep all keys from either table (option 1), only the keys that appear in both tables (option 2), only keys in the existing table (option 3), or only the keys in the new table (option 4). This allows the user to keep the 100 rows for those with `student id`, or 90 rows for those with `sis id`, the intersection, or the union.

side note: this scenario also casuses an error in OnTask. See issue #41.

In light of #41, this is presently hypothetical, but: If there isn't perfect overlap in the key values, and both key columns are retained separately rather than merged, how should the user go about joining a 3rd table that has some matches in both of the prior 2 key columns? For example, we want all rows (merge method \# 1) from all 3 tables, with the key columns `student id`, `student number`, and `sis id` in the 3 tables. How should that be achieved using OnTask?

I think the root of the issue is that it is not transparent to the user that a merge operation on 2 columns with the same name will "merge" the values to produce one result column, whereas a merge operation on 2 columns with different names will "align" those columns and produce 2 result columns.

**Comment by abelardopardo** [comment] 2018-05-18 01:41
I agree. The root of the problem is the lack of transparency on how the columns are merged with they have identical names vs when they have different names. The platform now performs two different operations that result in different outcomes, and it is not clearly represented in the instructions/documentation. We'll incorporate this both in how the operations are represented in the Step 4 screen, but also reflected in the figures that appear documenting each option. 

We'll look to issue #41 in parallel.

Thanks for the clear insight. Very useful.

**Comment by abelardopardo** [comment] 2018-05-23 04:51
Solved in Version 2.6.1

**Closed by abelardopardo** 2018-05-23 04:51 UTC
Labels: enhancement, fix on next release
